spring:
  profiles:
    group:
      development:
        - "local"
        - "common"
        - "springdoc"
      production:
        - "docker"
        - "common"
        - "springdoc"
    default: "development"

---
spring:
  application:
    name: micro-api
  config:
    activate:
      on-profile: common
  jmx:
    enabled: true
  main:
    web-application-type: reactive
  web:
    resources:
      chain:
        strategy:
          content:
            paths: /webjars/swagger-ui/**.*
  webflux:
    hiddenmethod:
      filter:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: springdoc
springdoc:
  api-docs:
    resolve-schema-properties: true
  model-and-view-allowed: true
  swagger-ui:
    display-query-params: true
    displayOperationId: true
    displayRequestDuration: true
    path: /swagger-ui.html
    show-common-extensions: true
    show-extensions: true
  show-actuator: true

---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      port: 35219
    restart:
      poll-interval: 1000
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/catcafe?useSSL=false&autoReconnect=true&reWriteBatchedInserts=true
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
server:
  port: 9001
  servlet:
    context-path: /CatCafeApi
  http2:
    enabled: true
logging:
  level:
    root: INFO
    redis:
      clients: TRACE
    org:
      springframework:
        data:
          r2dbc: DEBUG
  file:
    name: micro-api.log
---
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/catcafe?useSSL=false&autoReconnect=true&reWriteBatchedInserts=true
    username: root
    password: root
  redis:
    database: 1
    host: redis
    port: 6379
server:
  port: 9001
  servlet:
    context-path: /CatCafeApi
  http2:
    enabled: true
logging:
  level:
    root: INFO
    redis:
      clients: TRACE
    org:
      springframework:
        data:
          r2dbc: DEBUG
  file:
    name: micro-api.log
